name: template_block
version: 0.1.0
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: The 'template block' is a template engine for the code generators with a very simple syntax.
homepage: https://github.com/mezoni/template_block
